DEBUG 2021-06-11 09:18:59.396 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-11 09:18:59.397 UTC: 	 Running on: Linux lxplus711.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-11 09:18:59.397 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-11 09:18:59.398 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-06-11 09:18:59.399 UTC: 	 Will use CRAB configuration file crabcode_2018/MuonEG_Run2018A_cfg.py
DEBUG 2021-06-11 09:18:59.399 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-11 09:18:59.415 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-11 09:18:59.434 UTC: 	 Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018A' already exists 
Please change the requestName in the config file
ERROR 2021-06-11 09:18:59.435 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/ClientUtilities.py", line 399, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018A' already exists 
Please change the requestName in the config file
INFO 2021-06-11 09:18:59.439 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab.log
DEBUG 2021-06-11 09:18:59.833 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-11 09:18:59.833 UTC: 	 Running on: Linux lxplus711.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-11 09:18:59.833 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-11 09:18:59.834 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-06-11 09:18:59.835 UTC: 	 Will use CRAB configuration file crabcode_2018/MuonEG_Run2018B_cfg.py
DEBUG 2021-06-11 09:18:59.835 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-11 09:18:59.864 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-11 09:18:59.865 UTC: 	 Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018B' already exists 
Please change the requestName in the config file
ERROR 2021-06-11 09:18:59.865 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/ClientUtilities.py", line 399, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018B' already exists 
Please change the requestName in the config file
INFO 2021-06-11 09:18:59.868 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab.log
DEBUG 2021-06-11 09:19:00.275 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-11 09:19:00.276 UTC: 	 Running on: Linux lxplus711.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-11 09:19:00.276 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-11 09:19:00.276 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-06-11 09:19:00.277 UTC: 	 Will use CRAB configuration file crabcode_2018/MuonEG_Run2018C_cfg.py
DEBUG 2021-06-11 09:19:00.278 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-11 09:19:00.297 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-11 09:19:00.344 UTC: 	 Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018C' already exists 
Please change the requestName in the config file
ERROR 2021-06-11 09:19:00.345 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/ClientUtilities.py", line 399, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018C' already exists 
Please change the requestName in the config file
INFO 2021-06-11 09:19:00.348 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab.log
DEBUG 2021-06-11 09:19:00.743 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-11 09:19:00.743 UTC: 	 Running on: Linux lxplus711.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-11 09:19:00.743 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-11 09:19:00.744 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-06-11 09:19:00.745 UTC: 	 Will use CRAB configuration file crabcode_2018/MuonEG_Run2018D_cfg.py
DEBUG 2021-06-11 09:19:00.745 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-11 09:19:00.800 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-11 09:19:00.801 UTC: 	 Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018D' already exists 
Please change the requestName in the config file
ERROR 2021-06-11 09:19:00.801 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/ClientUtilities.py", line 399, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab2018/crab_MuonEG_Run2018D' already exists 
Please change the requestName in the config file
INFO 2021-06-11 09:19:00.805 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab.log
DEBUG 2021-06-18 06:31:43.136 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-18 06:31:43.136 UTC: 	 Running on: Linux lxplus751.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-18 06:31:43.136 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-18 06:31:43.137 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-06-18 06:31:43.137 UTC: 	 Will use CRAB configuration file crabcode_2018/MuonEG_Run2018A_cfg.py
DEBUG 2021-06-18 06:31:43.138 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-18 06:31:43.141 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-06-18 06:31:43.141 UTC: 	 Cannot find the file ./WWG_crab_script_fakable specified in the JobType.scriptExe configuration parameter.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2021-06-18 06:31:43.141 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Cannot find the file ./WWG_crab_script_fakable specified in the JobType.scriptExe configuration parameter.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2021-06-18 06:31:43.144 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakelepton_crab/crab.log
DEBUG 2021-06-22 16:10:04.479 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-06-22 16:10:04.480 UTC: 	 Running on: Linux lxplus733.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-22 16:10:04.480 UTC: 	 Executing command: 'status'
DEBUG 2021-06-22 16:10:04.480 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
DEBUG 2021-07-06 09:44:41.966 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-06 09:44:41.967 UTC: 	 Running on: Linux lxplus714.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-06 09:44:41.967 UTC: 	 Executing command: 'status'
DEBUG 2021-07-06 09:44:41.967 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-07-06 09:44:41.968 UTC: 	 Error: crab2018/crab_EGamma_Run2018D is not a valid CRAB project directory.
ERROR 2021-07-06 09:44:41.968 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2018/crab_EGamma_Run2018D is not a valid CRAB project directory.
INFO 2021-07-06 09:44:41.994 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakerate_crab/crab.log
DEBUG 2021-07-07 07:29:57.896 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-07 07:29:57.897 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-07 07:29:57.897 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-07-07 07:29:57.898 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-07-07 07:29:57.902 UTC: 	 Error: crab2018/crab_EGamma_Run2018D is not a valid CRAB project directory.
ERROR 2021-07-07 07:29:57.902 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/resubmit.py", line 26, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2018/crab_EGamma_Run2018D is not a valid CRAB project directory.
INFO 2021-07-07 07:29:57.960 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakerate_crab/crab.log
DEBUG 2021-07-07 08:15:17.725 UTC: 	 CRAB Client version: v3.210610
DEBUG 2021-07-07 08:15:17.726 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-07-07 08:15:17.726 UTC: 	 Executing command: 'status'
DEBUG 2021-07-07 08:15:17.727 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-07-07 08:15:17.729 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakerate_crab/crab2018/crab_TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8_2018
ERROR 2021-07-07 08:15:17.729 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 650, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210610.01/lib/CRABClient/Commands/SubCommand.py", line 512, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakerate_crab/crab2018/crab_TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8_2018
INFO 2021-07-07 08:15:17.739 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakerate_crab/crab.log
DEBUG 2021-08-28 14:23:16.910 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-28 14:23:16.911 UTC: 	 Running on: Linux lxplus728.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-28 14:23:16.911 UTC: 	 Executing command: 'checkwrite'
DEBUG 2021-08-28 14:23:16.912 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
DEBUG 2021-08-28 14:23:16.937 UTC: 	 Checking credentials
DEBUG 2021-08-28 14:23:16.938 UTC: 	 Found proxy file /tmp/x509up_u110046
DEBUG 2021-08-28 14:23:16.938 UTC: 	 Getting proxy life time left
DEBUG 2021-08-28 14:23:17.845 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u110046 -timeleft
 output : 601909

 error: 
 retcode : 0
DEBUG 2021-08-28 14:23:18.653 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u110046 -actimeleft
 output : 601908

 error: 
 retcode : 0
DEBUG 2021-08-28 14:23:18.654 UTC: 	 Proxy lifetime 601909 secs is different from voms extension lifetime 601908 secs for proxy: /tmp/x509up_u110046
DEBUG 2021-08-28 14:23:18.654 UTC: 	 Proxy valid for 167:11:48 hours
DEBUG 2021-08-28 14:23:19.466 UTC: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u110046 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
ERROR 2021-08-28 14:23:19.467 UTC: 	 Error: Please specify the site where to check the write permissions. Use the --site option.
ERROR 2021-08-28 14:23:19.467 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/checkwrite.py", line 21, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 373, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/checkwrite.py", line 289, in validateOptions
    raise ex
MissingOptionException: [91mError[0m: Please specify the site where to check the write permissions. Use the --site option.
INFO 2021-08-28 14:23:19.521 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-08-28 14:23:42.057 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-28 14:23:42.057 UTC: 	 Running on: Linux lxplus728.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-28 14:23:42.057 UTC: 	 Executing command: 'checkwrite'
DEBUG 2021-08-28 14:23:42.057 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
DEBUG 2021-08-28 14:23:42.066 UTC: 	 Checking credentials
DEBUG 2021-08-28 14:23:42.066 UTC: 	 Found proxy file /tmp/x509up_u110046
DEBUG 2021-08-28 14:23:42.066 UTC: 	 Getting proxy life time left
DEBUG 2021-08-28 14:23:42.781 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u110046 -timeleft
 output : 601884

 error: 
 retcode : 0
DEBUG 2021-08-28 14:23:43.488 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u110046 -actimeleft
 output : 601883

 error: 
 retcode : 0
DEBUG 2021-08-28 14:23:43.489 UTC: 	 Proxy lifetime 601884 secs is different from voms extension lifetime 601883 secs for proxy: /tmp/x509up_u110046
DEBUG 2021-08-28 14:23:43.489 UTC: 	 Proxy valid for 167:11:23 hours
DEBUG 2021-08-28 14:23:44.197 UTC: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u110046 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2021-08-28 14:23:44.198 UTC: 	 Command use: checkwrite
DEBUG 2021-08-28 14:23:44.198 UTC: 	 Options use: ['--site', 'T3_CH_CERNBOX']
DEBUG 2021-08-28 14:23:44.198 UTC: 	 Instance is None
DEBUG 2021-08-28 14:23:44.198 UTC: 	 Server base url is None
DEBUG 2021-08-28 14:23:44.198 UTC: 	 Retrieving username ...
DEBUG 2021-08-28 14:23:44.198 UTC: 	 Retrieving username from CRIC...
DEBUG 2021-08-28 14:23:44.956 UTC: 	 username is yian
INFO 2021-08-28 14:23:44.957 UTC: 	 Will check write permission in the default location /store/user/<username>
INFO 2021-08-28 14:23:44.957 UTC: 	 Validating LFN /store/user/yian...
INFO 2021-08-28 14:23:44.957 UTC: 	 LFN /store/user/yian is valid.
INFO 2021-08-28 14:23:44.972 UTC: 	 Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
INFO 2021-08-28 14:23:44.973 UTC: 	 Will check write permission in /store/user/yian on site T3_CH_CERNBOX
INFO 2021-08-28 14:23:48.595 UTC: 	 Will use PFN: gsiftp://eosuserftp.cern.ch:2811/gsiftp:/eosuserftp.cern.ch/eos/user/y/yian/crab3checkwrite_20210828_162344/crab3checkwrite_20210828_162344.tmp
INFO 2021-08-28 14:23:48.596 UTC: 	 
Attempting to create (dummy) directory crab3checkwrite_20210828_162344 and copy (dummy) file crab3checkwrite_20210828_162344.tmp to /store/user/yian

INFO 2021-08-28 14:23:48.600 UTC: 	 Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-copy -p -v -t 180 file:///afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab3checkwrite_20210828_162344.tmp 'gsiftp://eosuserftp.cern.ch:2811/gsiftp:/eosuserftp.cern.ch/eos/user/y/yian/crab3checkwrite_20210828_162344/crab3checkwrite_20210828_162344.tmp'
INFO 2021-08-28 14:23:48.601 UTC: 	 Please wait...
INFO 2021-08-28 14:23:49.465 UTC: 	 Failed running copy command
INFO 2021-08-28 14:23:49.465 UTC: 	   Stdout:
    Copying 85 bytes file:///afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab3checkwrite_20210828_162344.tmp => gsiftp://eosuserftp.cern.ch:2811/gsiftp:/eosuserftp.cern.ch/eos/user/y/yian/crab3checkwrite_20210828_162344/crab3checkwrite_20210828_162344.tmp
    event: [1630160629445] BOTH   GFAL2:CORE:COPY	LIST:ENTER	
    event: [1630160629445] BOTH   GFAL2:CORE:COPY	LIST:ITEM	file:///afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab3checkwrite_20210828_162344.tmp => gsiftp://eosuserftp.cern.ch:2811/gsiftp:/eosuserftp.cern.ch/eos/user/y/yian/crab3checkwrite_20210828_162344/crab3checkwrite_20210828_162344.tmp
    event: [1630160629445] BOTH   GFAL2:CORE:COPY	LIST:EXIT	
    
INFO 2021-08-28 14:23:49.465 UTC: 	   Stderr:
    gfal-copy error: 13 (Permission denied) - globus_ftp_client: the server responded with an error 550 550-GlobusError: v=1 c=PERMISSION_DENIED  550-GridFTP-Errno: 13  550-GridFTP-Reason: System error in stat  550-GridFTP-Error-String: Permission denied  550 End.   
    
INFO 2021-08-28 14:23:49.593 UTC: 	 
Checkwrite Result:
INFO 2021-08-28 14:23:49.594 UTC: 	 Error: Unable to write in /store/user/yian on site T3_CH_CERNBOX
       You may want to contact the site administrators sending them the 'crab checkwrite' output as printed above.
INFO 2021-08-28 14:23:49.594 UTC: 	 Note: You cannot write to a site if you did not ask permission.
INFO 2021-08-28 14:23:50.865 UTC: 	 Additional diagnostic info for CERN EOS
== id ==>:
uid=110046(yian) gid=1399(zh) groups=1399(zh),1092690190 context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
== voms-proxy-info -all ==>:
subject   : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yian/CN=826694/CN=Ying An/CN=717960819
issuer    : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yian/CN=826694/CN=Ying An
identity  : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yian/CN=826694/CN=Ying An
type      : RFC3820 compliant impersonation proxy
strength  : 2048
path      : /tmp/x509up_u110046
timeleft  : 167:11:16
key usage : Digital Signature, Key Encipherment
=== VO cms extension information ===
VO        : cms
subject   : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yian/CN=826694/CN=Ying An
issuer    : /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
attribute : /cms/Role=NULL/Capability=NULL
timeleft  : 167:11:16
uri       : lcg-voms2.cern.ch:15002

== uberftp eoscmsftp.cern.ch pwd ==>:
220 eoscmsftp10.cern.ch GridFTP Server 13.21 (gcc64, 1607703417-0) [Grid Community Toolkit 6.2] ready.
230 User yian logged in.
/afs/cern.ch/user/y/yian

DEBUG 2021-08-28 14:24:29.040 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-28 14:24:29.040 UTC: 	 Running on: Linux lxplus728.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-28 14:24:29.040 UTC: 	 Executing command: 'checkwrite'
DEBUG 2021-08-28 14:24:29.042 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
DEBUG 2021-08-28 14:24:29.055 UTC: 	 Checking credentials
DEBUG 2021-08-28 14:24:29.056 UTC: 	 Found proxy file /tmp/x509up_u110046
DEBUG 2021-08-28 14:24:29.056 UTC: 	 Getting proxy life time left
DEBUG 2021-08-28 14:24:29.766 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u110046 -timeleft
 output : 601837

 error: 
 retcode : 0
DEBUG 2021-08-28 14:24:30.473 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u110046 -actimeleft
 output : 601836

 error: 
 retcode : 0
DEBUG 2021-08-28 14:24:30.474 UTC: 	 Proxy lifetime 601837 secs is different from voms extension lifetime 601836 secs for proxy: /tmp/x509up_u110046
DEBUG 2021-08-28 14:24:30.474 UTC: 	 Proxy valid for 167:10:36 hours
DEBUG 2021-08-28 14:24:31.183 UTC: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u110046 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2021-08-28 14:24:31.184 UTC: 	 Command use: checkwrite
DEBUG 2021-08-28 14:24:31.184 UTC: 	 Options use: ['--site', 'T2_CH_CERN']
DEBUG 2021-08-28 14:24:31.184 UTC: 	 Instance is None
DEBUG 2021-08-28 14:24:31.184 UTC: 	 Server base url is None
DEBUG 2021-08-28 14:24:31.184 UTC: 	 Retrieving username ...
DEBUG 2021-08-28 14:24:31.184 UTC: 	 Retrieving username from CRIC...
DEBUG 2021-08-28 14:24:31.895 UTC: 	 username is yian
INFO 2021-08-28 14:24:31.895 UTC: 	 Will check write permission in the default location /store/user/<username>
INFO 2021-08-28 14:24:31.896 UTC: 	 Validating LFN /store/user/yian...
INFO 2021-08-28 14:24:31.896 UTC: 	 LFN /store/user/yian is valid.
INFO 2021-08-28 14:24:31.903 UTC: 	 Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
INFO 2021-08-28 14:24:31.904 UTC: 	 Will check write permission in /store/user/yian on site T2_CH_CERN
INFO 2021-08-28 14:24:33.787 UTC: 	 Will use PFN: gsiftp://eoscmsftp.cern.ch:2811/eos/cms/store/user/yian/crab3checkwrite_20210828_162431/crab3checkwrite_20210828_162431.tmp
INFO 2021-08-28 14:24:33.787 UTC: 	 
Attempting to create (dummy) directory crab3checkwrite_20210828_162431 and copy (dummy) file crab3checkwrite_20210828_162431.tmp to /store/user/yian

INFO 2021-08-28 14:24:33.792 UTC: 	 Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-copy -p -v -t 180 file:///afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab3checkwrite_20210828_162431.tmp 'gsiftp://eoscmsftp.cern.ch:2811/eos/cms/store/user/yian/crab3checkwrite_20210828_162431/crab3checkwrite_20210828_162431.tmp'
INFO 2021-08-28 14:24:33.792 UTC: 	 Please wait...
INFO 2021-08-28 14:24:34.724 UTC: 	 
Successfully created directory crab3checkwrite_20210828_162431 and copied file crab3checkwrite_20210828_162431.tmp to /store/user/yian
INFO 2021-08-28 14:24:34.725 UTC: 	 
Attempting to delete file gsiftp://eoscmsftp.cern.ch:2811/eos/cms/store/user/yian/crab3checkwrite_20210828_162431/crab3checkwrite_20210828_162431.tmp

INFO 2021-08-28 14:24:34.725 UTC: 	 Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -v -t 180 'gsiftp://eoscmsftp.cern.ch:2811/eos/cms/store/user/yian/crab3checkwrite_20210828_162431/crab3checkwrite_20210828_162431.tmp'
INFO 2021-08-28 14:24:34.725 UTC: 	 Please wait...
INFO 2021-08-28 14:24:35.578 UTC: 	 
Successfully deleted file gsiftp://eoscmsftp.cern.ch:2811/eos/cms/store/user/yian/crab3checkwrite_20210828_162431/crab3checkwrite_20210828_162431.tmp
INFO 2021-08-28 14:24:35.579 UTC: 	 
Attempting to delete directory gsiftp://eoscmsftp.cern.ch:2811/eos/cms/store/user/yian/crab3checkwrite_20210828_162431/

INFO 2021-08-28 14:24:35.579 UTC: 	 Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -r -v -t 180 'gsiftp://eoscmsftp.cern.ch:2811/eos/cms/store/user/yian/crab3checkwrite_20210828_162431/'
INFO 2021-08-28 14:24:35.579 UTC: 	 Please wait...
INFO 2021-08-28 14:24:36.319 UTC: 	 
Successfully deleted directory gsiftp://eoscmsftp.cern.ch:2811/eos/cms/store/user/yian/crab3checkwrite_20210828_162431/
INFO 2021-08-28 14:24:36.378 UTC: 	 
Checkwrite Result:
INFO 2021-08-28 14:24:36.379 UTC: 	 Success: Able to write in /store/user/yian on site T2_CH_CERN
DEBUG 2021-08-28 14:24:44.093 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-28 14:24:44.094 UTC: 	 Running on: Linux lxplus728.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-28 14:24:44.094 UTC: 	 Executing command: 'checkwrite'
DEBUG 2021-08-28 14:24:44.094 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
DEBUG 2021-08-28 14:24:44.101 UTC: 	 Checking credentials
DEBUG 2021-08-28 14:24:44.102 UTC: 	 Found proxy file /tmp/x509up_u110046
DEBUG 2021-08-28 14:24:44.102 UTC: 	 Getting proxy life time left
DEBUG 2021-08-28 14:24:44.807 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u110046 -timeleft
 output : 601822

 error: 
 retcode : 0
DEBUG 2021-08-28 14:24:45.515 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u110046 -actimeleft
 output : 601821

 error: 
 retcode : 0
DEBUG 2021-08-28 14:24:45.515 UTC: 	 Proxy lifetime 601822 secs is different from voms extension lifetime 601821 secs for proxy: /tmp/x509up_u110046
DEBUG 2021-08-28 14:24:45.515 UTC: 	 Proxy valid for 167:10:21 hours
DEBUG 2021-08-28 14:24:46.225 UTC: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u110046 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2021-08-28 14:24:46.226 UTC: 	 Command use: checkwrite
DEBUG 2021-08-28 14:24:46.226 UTC: 	 Options use: ['--site', 'T2_CN_Beijing']
DEBUG 2021-08-28 14:24:46.226 UTC: 	 Instance is None
DEBUG 2021-08-28 14:24:46.226 UTC: 	 Server base url is None
DEBUG 2021-08-28 14:24:46.226 UTC: 	 Retrieving username ...
DEBUG 2021-08-28 14:24:46.226 UTC: 	 Retrieving username from CRIC...
DEBUG 2021-08-28 14:24:46.955 UTC: 	 username is yian
INFO 2021-08-28 14:24:46.955 UTC: 	 Will check write permission in the default location /store/user/<username>
INFO 2021-08-28 14:24:46.955 UTC: 	 Validating LFN /store/user/yian...
INFO 2021-08-28 14:24:46.956 UTC: 	 LFN /store/user/yian is valid.
INFO 2021-08-28 14:24:46.969 UTC: 	 Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
INFO 2021-08-28 14:24:46.969 UTC: 	 Will check write permission in /store/user/yian on site T2_CN_Beijing
INFO 2021-08-28 14:24:49.204 UTC: 	 Will use PFN: gsiftp://ccsrm.ihep.ac.cn:2811/dpm/ihep.ac.cn/home/cms/store/user/yian/crab3checkwrite_20210828_162446/crab3checkwrite_20210828_162446.tmp
INFO 2021-08-28 14:24:49.204 UTC: 	 
Attempting to create (dummy) directory crab3checkwrite_20210828_162446 and copy (dummy) file crab3checkwrite_20210828_162446.tmp to /store/user/yian

INFO 2021-08-28 14:24:49.209 UTC: 	 Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-copy -p -v -t 180 file:///afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab3checkwrite_20210828_162446.tmp 'gsiftp://ccsrm.ihep.ac.cn:2811/dpm/ihep.ac.cn/home/cms/store/user/yian/crab3checkwrite_20210828_162446/crab3checkwrite_20210828_162446.tmp'
INFO 2021-08-28 14:24:49.209 UTC: 	 Please wait...
INFO 2021-08-28 14:24:54.670 UTC: 	 
Successfully created directory crab3checkwrite_20210828_162446 and copied file crab3checkwrite_20210828_162446.tmp to /store/user/yian
INFO 2021-08-28 14:24:54.671 UTC: 	 
Attempting to delete file gsiftp://ccsrm.ihep.ac.cn:2811/dpm/ihep.ac.cn/home/cms/store/user/yian/crab3checkwrite_20210828_162446/crab3checkwrite_20210828_162446.tmp

INFO 2021-08-28 14:24:54.671 UTC: 	 Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -v -t 180 'gsiftp://ccsrm.ihep.ac.cn:2811/dpm/ihep.ac.cn/home/cms/store/user/yian/crab3checkwrite_20210828_162446/crab3checkwrite_20210828_162446.tmp'
INFO 2021-08-28 14:24:54.671 UTC: 	 Please wait...
INFO 2021-08-28 14:24:57.773 UTC: 	 
Successfully deleted file gsiftp://ccsrm.ihep.ac.cn:2811/dpm/ihep.ac.cn/home/cms/store/user/yian/crab3checkwrite_20210828_162446/crab3checkwrite_20210828_162446.tmp
INFO 2021-08-28 14:24:57.773 UTC: 	 
Attempting to delete directory gsiftp://ccsrm.ihep.ac.cn:2811/dpm/ihep.ac.cn/home/cms/store/user/yian/crab3checkwrite_20210828_162446/

INFO 2021-08-28 14:24:57.773 UTC: 	 Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-rm -r -v -t 180 'gsiftp://ccsrm.ihep.ac.cn:2811/dpm/ihep.ac.cn/home/cms/store/user/yian/crab3checkwrite_20210828_162446/'
INFO 2021-08-28 14:24:57.773 UTC: 	 Please wait...
INFO 2021-08-28 14:25:02.140 UTC: 	 
Successfully deleted directory gsiftp://ccsrm.ihep.ac.cn:2811/dpm/ihep.ac.cn/home/cms/store/user/yian/crab3checkwrite_20210828_162446/
INFO 2021-08-28 14:25:02.175 UTC: 	 
Checkwrite Result:
INFO 2021-08-28 14:25:02.175 UTC: 	 Success: Able to write in /store/user/yian on site T2_CN_Beijing
DEBUG 2021-08-28 14:28:37.535 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-28 14:28:37.535 UTC: 	 Running on: Linux lxplus740.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-28 14:28:37.535 UTC: 	 Executing command: 'submit'
DEBUG 2021-08-28 14:28:37.535 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-08-28 14:28:37.536 UTC: 	 CRAB configuration file crabcode_2017/SignleElectron_Run2017B_cfg.py not found.
ERROR 2021-08-28 14:28:37.536 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabcode_2017/SignleElectron_Run2017B_cfg.py not found.
INFO 2021-08-28 14:28:37.563 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-08-28 14:28:37.897 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-28 14:28:37.897 UTC: 	 Running on: Linux lxplus740.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-28 14:28:37.897 UTC: 	 Executing command: 'submit'
DEBUG 2021-08-28 14:28:37.898 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-08-28 14:28:37.899 UTC: 	 CRAB configuration file crabcode_2017/SignleElectron_Run2017C_cfg.py not found.
ERROR 2021-08-28 14:28:37.899 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabcode_2017/SignleElectron_Run2017C_cfg.py not found.
INFO 2021-08-28 14:28:37.901 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-08-28 14:28:38.243 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-28 14:28:38.244 UTC: 	 Running on: Linux lxplus740.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-28 14:28:38.244 UTC: 	 Executing command: 'submit'
DEBUG 2021-08-28 14:28:38.244 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-08-28 14:28:38.245 UTC: 	 CRAB configuration file crabcode_2017/SignleElectron_Run2017D_cfg.py not found.
ERROR 2021-08-28 14:28:38.245 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabcode_2017/SignleElectron_Run2017D_cfg.py not found.
INFO 2021-08-28 14:28:38.247 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-08-28 14:28:38.586 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-28 14:28:38.586 UTC: 	 Running on: Linux lxplus740.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-28 14:28:38.586 UTC: 	 Executing command: 'submit'
DEBUG 2021-08-28 14:28:38.587 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-08-28 14:28:38.587 UTC: 	 CRAB configuration file crabcode_2017/SignleElectron_Run2017E_cfg.py not found.
ERROR 2021-08-28 14:28:38.588 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabcode_2017/SignleElectron_Run2017E_cfg.py not found.
INFO 2021-08-28 14:28:38.589 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-08-28 14:28:38.936 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-28 14:28:38.936 UTC: 	 Running on: Linux lxplus740.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-28 14:28:38.936 UTC: 	 Executing command: 'submit'
DEBUG 2021-08-28 14:28:38.936 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-08-28 14:28:38.937 UTC: 	 CRAB configuration file crabcode_2017/SignleElectron_Run2017F_cfg.py not found.
ERROR 2021-08-28 14:28:38.937 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabcode_2017/SignleElectron_Run2017F_cfg.py not found.
INFO 2021-08-28 14:28:38.939 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-08-28 14:44:45.021 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-28 14:44:45.022 UTC: 	 Running on: Linux lxplus728.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-28 14:44:45.022 UTC: 	 Executing command: 'checkwrite'
DEBUG 2021-08-28 14:44:45.022 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
DEBUG 2021-08-28 14:44:45.041 UTC: 	 Checking credentials
DEBUG 2021-08-28 14:44:45.041 UTC: 	 Found proxy file /tmp/x509up_u110046
DEBUG 2021-08-28 14:44:45.041 UTC: 	 Getting proxy life time left
DEBUG 2021-08-28 14:44:45.848 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u110046 -timeleft
 output : 600621

 error: 
 retcode : 0
DEBUG 2021-08-28 14:44:46.558 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u110046 -actimeleft
 output : 600620

 error: 
 retcode : 0
DEBUG 2021-08-28 14:44:46.558 UTC: 	 Proxy lifetime 600621 secs is different from voms extension lifetime 600620 secs for proxy: /tmp/x509up_u110046
DEBUG 2021-08-28 14:44:46.558 UTC: 	 Proxy valid for 166:50:20 hours
DEBUG 2021-08-28 14:44:47.265 UTC: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u110046 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2021-08-28 14:44:47.265 UTC: 	 Command use: checkwrite
DEBUG 2021-08-28 14:44:47.266 UTC: 	 Options use: ['--site', 'T3\xe2\x80\x942_CH_CERNBOX']
DEBUG 2021-08-28 14:44:47.266 UTC: 	 Instance is None
DEBUG 2021-08-28 14:44:47.266 UTC: 	 Server base url is None
DEBUG 2021-08-28 14:44:47.266 UTC: 	 Retrieving username ...
DEBUG 2021-08-28 14:44:47.266 UTC: 	 Retrieving username from CRIC...
DEBUG 2021-08-28 14:44:47.991 UTC: 	 username is yian
INFO 2021-08-28 14:44:47.992 UTC: 	 Will check write permission in the default location /store/user/<username>
INFO 2021-08-28 14:44:47.992 UTC: 	 Validating LFN /store/user/yian...
INFO 2021-08-28 14:44:47.992 UTC: 	 LFN /store/user/yian is valid.
INFO 2021-08-28 14:44:48.005 UTC: 	 Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
INFO 2021-08-28 14:44:48.006 UTC: 	 Will check write permission in /store/user/yian on site T3—2_CH_CERNBOX
INFO 2021-08-28 14:44:50.168 UTC: 	 PFN lookup failed
INFO 2021-08-28 14:44:50.169 UTC: 	   Stderr:
      File "/tmp/lfn2pfn-HSeXme.py", line 4
    SyntaxError: Non-ASCII character '\xe2' in file /tmp/lfn2pfn-HSeXme.py on line 4, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
    
DEBUG 2021-08-28 16:05:42.740 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-28 16:05:42.741 UTC: 	 Running on: Linux lxplus734.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-28 16:05:42.741 UTC: 	 Executing command: 'submit'
DEBUG 2021-08-28 16:05:42.742 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-08-28 16:05:42.747 UTC: 	 CRAB configuration file crabcode_2017/TT not found.
ERROR 2021-08-28 16:05:42.747 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabcode_2017/TT not found.
INFO 2021-08-28 16:05:42.783 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-08-28 16:05:46.592 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-28 16:05:46.592 UTC: 	 Running on: Linux lxplus734.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-28 16:05:46.592 UTC: 	 Executing command: 'submit'
DEBUG 2021-08-28 16:05:46.592 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
INFO 2021-08-28 16:05:46.594 UTC: 	 Will use CRAB configuration file crabcode_2017/TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8_2017_cfg.py
DEBUG 2021-08-28 16:05:46.594 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-08-28 16:05:46.606 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-08-28 16:05:46.609 UTC: 	 Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab2017/crab_TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8_2017' already exists 
Please change the requestName in the config file
ERROR 2021-08-28 16:05:46.609 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab2017/crab_TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8_2017' already exists 
Please change the requestName in the config file
INFO 2021-08-28 16:05:46.612 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-08-29 12:25:40.764 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-29 12:25:40.765 UTC: 	 Running on: Linux lxplus734.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-29 12:25:40.765 UTC: 	 Executing command: 'status'
DEBUG 2021-08-29 12:25:40.765 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-08-29 12:25:40.771 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
ERROR 2021-08-29 12:25:40.771 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
INFO 2021-08-29 12:25:40.872 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-08-29 12:29:41.644 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-29 12:29:41.645 UTC: 	 Running on: Linux lxplus734.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-29 12:29:41.645 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-08-29 12:29:41.645 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-08-29 12:29:41.649 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
ERROR 2021-08-29 12:29:41.649 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/resubmit.py", line 26, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
INFO 2021-08-29 12:29:41.659 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-08-30 11:43:37.648 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-30 11:43:37.649 UTC: 	 Running on: Linux lxplus748.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-30 11:43:37.649 UTC: 	 Executing command: 'status'
DEBUG 2021-08-30 11:43:37.649 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-08-30 11:43:37.650 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
ERROR 2021-08-30 11:43:37.650 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
INFO 2021-08-30 11:43:37.922 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-08-30 11:51:05.157 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-30 11:51:05.158 UTC: 	 Running on: Linux lxplus748.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-30 11:51:05.158 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-08-30 11:51:05.159 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-08-30 11:51:05.161 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
ERROR 2021-08-30 11:51:05.162 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/resubmit.py", line 26, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
INFO 2021-08-30 11:51:05.163 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-08-31 12:36:19.866 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-08-31 12:36:19.867 UTC: 	 Running on: Linux lxplus709.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-08-31 12:36:19.867 UTC: 	 Executing command: 'status'
DEBUG 2021-08-31 12:36:19.867 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-08-31 12:36:19.868 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
ERROR 2021-08-31 12:36:19.869 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
INFO 2021-08-31 12:36:19.974 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2021-09-02 06:22:16.078 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-02 06:22:16.079 UTC: 	 Running on: Linux lxplus747.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-09-02 06:22:16.079 UTC: 	 Executing command: 'status'
DEBUG 2021-09-02 06:22:16.079 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-09-02 06:22:16.080 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
ERROR 2021-09-02 06:22:16.080 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
INFO 2021-09-02 06:22:16.206 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 08:19:43.410 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 08:19:43.410 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 08:19:43.410 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 08:19:43.411 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 08:19:43.412 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017B is not a valid CRAB project directory.
ERROR 2022-01-28 08:19:43.412 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017B is not a valid CRAB project directory.
INFO 2022-01-28 08:19:43.485 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 08:19:43.901 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 08:19:43.901 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 08:19:43.901 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 08:19:43.901 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 08:19:43.902 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017C is not a valid CRAB project directory.
ERROR 2022-01-28 08:19:43.903 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017C is not a valid CRAB project directory.
INFO 2022-01-28 08:19:43.905 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 08:19:44.321 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 08:19:44.321 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 08:19:44.321 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 08:19:44.321 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 08:19:44.322 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017D is not a valid CRAB project directory.
ERROR 2022-01-28 08:19:44.322 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017D is not a valid CRAB project directory.
INFO 2022-01-28 08:19:44.325 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 08:19:44.733 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 08:19:44.733 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 08:19:44.733 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 08:19:44.734 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 08:19:44.734 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017E is not a valid CRAB project directory.
ERROR 2022-01-28 08:19:44.735 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017E is not a valid CRAB project directory.
INFO 2022-01-28 08:19:44.738 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 08:19:45.165 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 08:19:45.165 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 08:19:45.165 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 08:19:45.165 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 08:19:45.166 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017F is not a valid CRAB project directory.
ERROR 2022-01-28 08:19:45.166 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017F is not a valid CRAB project directory.
INFO 2022-01-28 08:19:45.169 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 08:19:45.578 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 08:19:45.578 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 08:19:45.579 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 08:19:45.579 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 08:19:45.580 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
ERROR 2022-01-28 08:19:45.580 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
INFO 2022-01-28 08:19:45.583 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 08:32:43.426 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 08:32:43.426 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 08:32:43.426 UTC: 	 Executing command: 'kill'
DEBUG 2022-01-28 08:32:43.426 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 08:32:43.428 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017B is not a valid CRAB project directory.
ERROR 2022-01-28 08:32:43.429 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017B is not a valid CRAB project directory.
INFO 2022-01-28 08:32:43.436 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 08:32:43.801 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 08:32:43.801 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 08:32:43.801 UTC: 	 Executing command: 'kill'
DEBUG 2022-01-28 08:32:43.802 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 08:32:43.802 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017C is not a valid CRAB project directory.
ERROR 2022-01-28 08:32:43.802 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017C is not a valid CRAB project directory.
INFO 2022-01-28 08:32:43.804 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 08:32:44.183 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 08:32:44.183 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 08:32:44.183 UTC: 	 Executing command: 'kill'
DEBUG 2022-01-28 08:32:44.184 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 08:32:44.184 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017D is not a valid CRAB project directory.
ERROR 2022-01-28 08:32:44.184 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017D is not a valid CRAB project directory.
INFO 2022-01-28 08:32:44.186 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 08:32:44.553 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 08:32:44.553 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 08:32:44.553 UTC: 	 Executing command: 'kill'
DEBUG 2022-01-28 08:32:44.553 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 08:32:44.554 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017E is not a valid CRAB project directory.
ERROR 2022-01-28 08:32:44.554 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017E is not a valid CRAB project directory.
INFO 2022-01-28 08:32:44.556 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 08:32:44.921 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 08:32:44.921 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 08:32:44.921 UTC: 	 Executing command: 'kill'
DEBUG 2022-01-28 08:32:44.921 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 08:32:44.922 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017F is not a valid CRAB project directory.
ERROR 2022-01-28 08:32:44.922 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017F is not a valid CRAB project directory.
INFO 2022-01-28 08:32:44.924 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 08:32:45.330 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 08:32:45.331 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 08:32:45.331 UTC: 	 Executing command: 'kill'
DEBUG 2022-01-28 08:32:45.331 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 08:32:45.332 UTC: 	 Error: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
ERROR 2022-01-28 08:32:45.332 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_DoubleMuon_Run2017H is not a valid CRAB project directory.
INFO 2022-01-28 08:32:45.334 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 09:02:45.656 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 09:02:45.656 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 09:02:45.656 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 09:02:45.657 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 09:02:45.657 UTC: 	 Error: crab2017/crab_SingleElectron_Run2017G is not a valid CRAB project directory.
ERROR 2022-01-28 09:02:45.658 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_SingleElectron_Run2017G is not a valid CRAB project directory.
INFO 2022-01-28 09:02:45.698 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 09:03:01.048 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 09:03:01.049 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 09:03:01.049 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 09:03:01.049 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 09:03:01.050 UTC: 	 Error: crab2017/crab_SingleMuon_Run2017G is not a valid CRAB project directory.
ERROR 2022-01-28 09:03:01.050 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_SingleMuon_Run2017G is not a valid CRAB project directory.
INFO 2022-01-28 09:03:01.053 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 09:12:56.457 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 09:12:56.458 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 09:12:56.458 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 09:12:56.458 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 09:12:56.459 UTC: 	 Error: crab2017/crab_SingleElectron_Run2017G is not a valid CRAB project directory.
ERROR 2022-01-28 09:12:56.459 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_SingleElectron_Run2017G is not a valid CRAB project directory.
INFO 2022-01-28 09:12:56.495 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 09:13:11.211 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 09:13:11.212 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 09:13:11.212 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 09:13:11.212 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 09:13:11.213 UTC: 	 Error: crab2017/crab_SingleMuon_Run2017G is not a valid CRAB project directory.
ERROR 2022-01-28 09:13:11.213 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_SingleMuon_Run2017G is not a valid CRAB project directory.
INFO 2022-01-28 09:13:11.217 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 09:41:15.249 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 09:41:15.249 UTC: 	 Running on: Linux lxplus773.cern.ch 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 09:41:15.249 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 09:41:15.249 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 09:41:15.250 UTC: 	 Error: crab2017/crab_SingleElectron_Run2017G is not a valid CRAB project directory.
ERROR 2022-01-28 09:41:15.250 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_SingleElectron_Run2017G is not a valid CRAB project directory.
INFO 2022-01-28 09:41:15.284 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 09:41:30.196 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 09:41:30.197 UTC: 	 Running on: Linux lxplus773.cern.ch 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 09:41:30.197 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 09:41:30.197 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 09:41:30.198 UTC: 	 Error: crab2017/crab_SingleMuon_Run2017G is not a valid CRAB project directory.
ERROR 2022-01-28 09:41:30.198 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_SingleMuon_Run2017G is not a valid CRAB project directory.
INFO 2022-01-28 09:41:30.200 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 12:44:45.097 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 12:44:45.097 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 12:44:45.097 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 12:44:45.098 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 12:44:45.098 UTC: 	 Error: crab2017/crab_SingleElectron_Run2017G is not a valid CRAB project directory.
ERROR 2022-01-28 12:44:45.099 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_SingleElectron_Run2017G is not a valid CRAB project directory.
INFO 2022-01-28 12:44:45.200 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 12:45:04.582 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 12:45:04.582 UTC: 	 Running on: Linux lxplus775.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 12:45:04.582 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 12:45:04.582 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 12:45:04.583 UTC: 	 Error: crab2017/crab_SingleMuon_Run2017G is not a valid CRAB project directory.
ERROR 2022-01-28 12:45:04.583 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_SingleMuon_Run2017G is not a valid CRAB project directory.
INFO 2022-01-28 12:45:04.586 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 13:01:04.152 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 13:01:04.153 UTC: 	 Running on: Linux lxplus752.cern.ch 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 13:01:04.153 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 13:01:04.153 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 13:01:04.154 UTC: 	 Error: crab2017/crab_SingleElectron_Run2017G is not a valid CRAB project directory.
ERROR 2022-01-28 13:01:04.154 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_SingleElectron_Run2017G is not a valid CRAB project directory.
INFO 2022-01-28 13:01:04.167 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-28 13:01:19.466 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-28 13:01:19.467 UTC: 	 Running on: Linux lxplus752.cern.ch 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-28 13:01:19.467 UTC: 	 Executing command: 'status'
DEBUG 2022-01-28 13:01:19.467 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-28 13:01:19.468 UTC: 	 Error: crab2017/crab_SingleMuon_Run2017G is not a valid CRAB project directory.
ERROR 2022-01-28 13:01:19.468 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_SingleMuon_Run2017G is not a valid CRAB project directory.
INFO 2022-01-28 13:01:19.471 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-30 00:29:57.204 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-30 00:29:57.205 UTC: 	 Running on: Linux lxplus784.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-30 00:29:57.205 UTC: 	 Executing command: 'remake'
DEBUG 2022-01-30 00:29:57.206 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
DEBUG 2022-01-30 00:29:57.207 UTC: 	 Checking credentials
DEBUG 2022-01-30 00:29:57.207 UTC: 	 Found proxy file /tmp/x509up_u110046
DEBUG 2022-01-30 00:29:57.207 UTC: 	 Getting proxy life time left
DEBUG 2022-01-30 00:29:57.208 UTC: 	 Executing command :
 voms-proxy-info --actimeleft --timeleft --file /tmp/x509up_u110046
DEBUG 2022-01-30 00:29:57.798 UTC: 	 output : 603985
603985

 error: 
 retcode : 0
DEBUG 2022-01-30 00:29:57.799 UTC: 	 Proxy valid for 167:46:25 hours
DEBUG 2022-01-30 00:29:57.886 UTC: 	 Encoded data for curl request: subresource=delegatedn
DEBUG 2022-01-30 00:29:57.887 UTC: 	 Executing command :
 curl -v -X GET -H "User-Agent: CRABClient/v3.211130" -H "Accept: */*" --data @/tmp/curlDataJtbp_B --cert "/tmp/x509up_u110046" --key "/tmp/x509up_u110046" --capath "/etc/grid-security/certificates/" "https://cmsweb.cern.ch:8443/crabserver/prod/info?subresource=delegatedn" | tee /dev/stderr 
DEBUG 2022-01-30 00:29:57.952 UTC: 	 output : {"result": [
 {"services": ["/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch|/DC=ch/DC=cern/OU=computers/CN=dciangot-tw.cern.ch"]}
]}

 error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 188.184.98.213...
* TCP_NODELAY set
* Connected to cmsweb.cern.ch (188.184.98.213) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: /etc/grid-security/certificates/
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [109 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [6224 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
{ [13495 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
} [6637 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
} [264 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: DC=ch; DC=cern; OU=computers; CN=cmsweb.cern.ch
*  start date: Feb  2 08:08:53 2021 GMT
*  expire date: Mar  9 08:08:53 2022 GMT
*  subjectAltName: host "cmsweb.cern.ch" matched cert's "cmsweb.cern.ch"
*  issuer: DC=ch; DC=cern; CN=CERN Grid Certification Authority
*  SSL certificate verify ok.
} [5 bytes data]
> GET /crabserver/prod/info?subresource=delegatedn HTTP/1.1
> Host: cmsweb.cern.ch:8443
> User-Agent: CRABClient/v3.211130
> Accept: */*
> Content-Length: 22
> Content-Type: application/x-www-form-urlencoded
> 
} [22 bytes data]
* upload completely sent off: 22 out of 22 bytes
{ [5 bytes data]
< HTTP/1.1 200 OK
< Date: Sun, 30 Jan 2022 00:29:57 GMT
< Server: nginx/1.17.10
< Content-Type: application/json
< Content-Length: 213
< Vary: Accept
< Cache-Control: max-age=3600
< X-Rest-Status: 100
< Etag: "de92dcb56f87dabbe30965e60a433c3f1b873eab"
< X-Rest-Time: 1934.290 us
< CMS-Server-Time: D=11893 t=1643502597938309
< 
{ [5 bytes data]
100   235  100   213  100    22   5325    550 --:--:-- --:--:-- --:--:--  5875
* Connection #0 to host cmsweb.cern.ch left intact
{"result": [
 {"services": ["/DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch|/DC=ch/DC=cern/OU=computers/CN=dciangot-tw.cern.ch"]}
]}

 retcode : 0
DEBUG 2022-01-30 00:29:57.953 UTC: 	 Registering user credentials on myproxy for /DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch|/DC=ch/DC=cern/OU=computers/CN=dciangot-tw.cern.ch
DEBUG 2022-01-30 00:29:57.953 UTC: 	 Executing command :
 voms-proxy-info --identity --file /tmp/x509up_u110046
DEBUG 2022-01-30 00:29:58.526 UTC: 	 output : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yian/CN=826694/CN=Ying An

 error: 
 retcode : 0
DEBUG 2022-01-30 00:29:58.526 UTC: 	 Getting myproxy life time left for b52ac606a6f7097e9b4b8f05a3a67cc69f8f291b
DEBUG 2022-01-30 00:29:58.527 UTC: 	 Executing command :
 myproxy-info -s myproxy.cern.ch -l b52ac606a6f7097e9b4b8f05a3a67cc69f8f291b
DEBUG 2022-01-30 00:29:58.953 UTC: 	 output : username: b52ac606a6f7097e9b4b8f05a3a67cc69f8f291b
owner: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yian/CN=826694/CN=Ying An
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch|/DC=ch/DC=cern/OU=computers/CN=dciangot-tw.cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=crab-(preprod|prod|dev)-tw(02|01).cern.ch|/DC=ch/DC=cern/OU=computers/CN=stefanov(m|m2).cern.ch|/DC=ch/DC=cern/OU=computers/CN=dciangot-tw.cern.ch
  timeleft: 466:02:29  (19.4 days)

 error: 
 retcode : 0
DEBUG 2022-01-30 00:29:58.953 UTC: 	 Myproxy is valid: 1677720
DEBUG 2022-01-30 00:29:58.954 UTC: 	 Result of myproxy credential check:
  Credential exists on myproxy: username: b52ac606a6f7097e9b4b8f05a3a67cc69f8f291b  - validity: 19 days, 10:02:00
DEBUG 2022-01-30 00:29:58.954 UTC: 	 Command use: remake
DEBUG 2022-01-30 00:29:58.954 UTC: 	 Options use: ['--task=220128_085252:yian_crab_SingleElectron_Run2017F']
DEBUG 2022-01-30 00:29:58.955 UTC: 	 Encoded data for curl request: subresource=version
DEBUG 2022-01-30 00:29:58.955 UTC: 	 Executing command :
 curl -v -X GET -H "User-Agent: CRABClient/v3.211130" -H "Accept: */*" --data @/tmp/curlDataHegonw --cert "/tmp/x509up_u110046" --key "/tmp/x509up_u110046" --capath "/etc/grid-security/certificates/" "https://cmsweb.cern.ch:8443/crabserver/prod/info?subresource=version" | tee /dev/stderr 
DEBUG 2022-01-30 00:29:59.042 UTC: 	 output : {"result": [
 ["3.3.19", "3.3.20", "v3", "development", "py3.220124"]
]}

 error:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 188.184.98.213...
* TCP_NODELAY set
* Connected to cmsweb.cern.ch (188.184.98.213) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: /etc/grid-security/certificates/
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [109 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [6224 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
{ [13495 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
} [6637 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
} [264 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: DC=ch; DC=cern; OU=computers; CN=cmsweb.cern.ch
*  start date: Feb  2 08:08:53 2021 GMT
*  expire date: Mar  9 08:08:53 2022 GMT
*  subjectAltName: host "cmsweb.cern.ch" matched cert's "cmsweb.cern.ch"
*  issuer: DC=ch; DC=cern; CN=CERN Grid Certification Authority
*  SSL certificate verify ok.
} [5 bytes data]
> GET /crabserver/prod/info?subresource=version HTTP/1.1
> Host: cmsweb.cern.ch:8443
> User-Agent: CRABClient/v3.211130
> Accept: */*
> Content-Length: 19
> Content-Type: application/x-www-form-urlencoded
> 
} [19 bytes data]
* upload completely sent off: 19 out of 19 bytes
{ [5 bytes data]
< HTTP/1.1 200 OK
< Date: Sun, 30 Jan 2022 00:29:59 GMT
< Server: nginx/1.17.10
< Content-Type: application/json
< Content-Length: 73
< Vary: Accept
< Cache-Control: max-age=3600
< X-Rest-Status: 100
< Etag: "3309a93c90cdb00bd297a532c9c67f645a0b4b24"
< X-Rest-Time: 1892.567 us
< CMS-Server-Time: D=24891 t=1643502599014657
< 
{ [5 bytes data]
100    92  100    73  100    19   1196    311 --:--:-- --:--:-- --:--:--  1533
* Connection #0 to host cmsweb.cern.ch left intact
{"result": [
 ["3.3.19", "3.3.20", "v3", "development", "py3.220124"]
]}

 retcode : 0
DEBUG 2022-01-30 00:29:59.043 UTC: 	 CRABClient version: v3.211130
DEBUG 2022-01-30 00:29:59.043 UTC: 	 Instance is prod
DEBUG 2022-01-30 00:29:59.043 UTC: 	 Server base url is cmsweb.cern.ch
DEBUG 2022-01-30 00:29:59.043 UTC: 	 Command api workflow
INFO 2022-01-30 00:29:59.043 UTC: 	 Remaking crab_SingleElectron_Run2017F folder.
INFO 2022-01-30 00:29:59.090 UTC: 	 Remaking .requestcache file.
INFO 2022-01-30 00:29:59.095 UTC: 	 Success: Finished remaking project directory crab_SingleElectron_Run2017F
INFO 2022-01-30 00:29:59.248 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
DEBUG 2022-01-30 08:39:21.354 UTC: 	 CRAB Client version: v3.211130
DEBUG 2022-01-30 08:39:21.355 UTC: 	 Running on: Linux lxplus731.cern.ch 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-01-30 08:39:21.355 UTC: 	 Executing command: 'resubmit'
DEBUG 2022-01-30 08:39:21.356 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2022-01-30 08:39:21.357 UTC: 	 Error: crab2017/crab_SingleMuon_Run2017V is not a valid CRAB project directory.
ERROR 2022-01-30 08:39:21.357 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/resubmit.py", line 30, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2017/crab_SingleMuon_Run2017V is not a valid CRAB project directory.
INFO 2022-01-30 08:39:21.395 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/WWG/2017/fakelepton_crab/crab.log
