DEBUG 2021-06-03 18:10:47.963 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-03 18:10:47.963 UTC: 	 Running on: Linux lxplus706.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-03 18:10:47.963 UTC: 	 Executing command: 'status'
DEBUG 2021-06-03 18:10:47.963 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-06-03 18:10:47.964 UTC: 	 Error: crab_DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_2018 is not a valid CRAB project directory.
ERROR 2021-06-03 18:10:47.965 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_2018 is not a valid CRAB project directory.
INFO 2021-06-03 18:10:47.968 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakephoton_crab/crab.log
DEBUG 2021-06-03 18:10:48.359 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-03 18:10:48.359 UTC: 	 Running on: Linux lxplus706.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-03 18:10:48.359 UTC: 	 Executing command: 'status'
DEBUG 2021-06-03 18:10:48.359 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-06-03 18:10:48.360 UTC: 	 Error: crab_TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8_2018 is not a valid CRAB project directory.
ERROR 2021-06-03 18:10:48.360 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8_2018 is not a valid CRAB project directory.
INFO 2021-06-03 18:10:48.362 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakephoton_crab/crab.log
DEBUG 2021-06-11 16:59:18.136 UTC: 	 CRAB Client version: v3.210601
DEBUG 2021-06-11 16:59:18.137 UTC: 	 Running on: Linux lxplus708.cern.ch 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-06-11 16:59:18.137 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-06-11 16:59:18.137 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-06-11 16:59:18.138 UTC: 	 Error: crab2018/crab_TT is not a valid CRAB project directory.
ERROR 2021-06-11 16:59:18.138 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/resubmit.py", line 26, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210601.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab2018/crab_TT is not a valid CRAB project directory.
INFO 2021-06-11 16:59:18.176 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakephoton_crab/crab.log
