DEBUG 2021-04-11 04:13:21.804 UTC: 	 CRAB Client version: v3.210127
DEBUG 2021-04-11 04:13:21.805 UTC: 	 Running on: Linux lxplus769.cern.ch 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-11 04:13:21.805 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-04-11 04:13:21.805 UTC: 	 Found CRAB cache file /afs/cern.ch/user/y/yian/.crab3
ERROR 2021-04-11 04:13:21.806 UTC: 	 Error: 'crab resubmit' command accepts at most 1 argument (a path to a CRAB project directory), 2 given.
ERROR 2021-04-11 04:13:21.806 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/resubmit.py", line 26, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/SubCommand.py", line 625, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: 'crab resubmit' command accepts at most 1 argument (a path to a CRAB project directory), 2 given.
INFO 2021-04-11 04:13:21.809 UTC: 	 Log file is /afs/cern.ch/work/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2018/fakephoton_crab/crab2018/crab.log
